### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [upollo/tag-manager-template#1]
https://github.com/upollo/tag-manager-template/blob/6f2d00ff92b46252e568bb16029e82ff787db0a1/template.tpl#L45

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by cayden-uw** [comment]
Hey @semisight , 

Thanks for flagging this. I have fixed this in #2.

Is there anything else we need to do as part of the review process?
